export const SOCKET_EVENTS = Object.freeze({
  ROOM_JOIN: 'room:join',
  ROOM_LEAVE: 'room:leave',
  ROOM_ERROR: 'room:error',
  EDITOR_STATE: 'editor:state',
  EDITOR_CHANGE: 'editor:change',
  EDITOR_UPDATE: 'editor:update',
  EDITOR_CONFLICT: 'editor:conflict',
  CURSOR_UPDATE: 'cursor:update',
  CURSOR_CLEAR: 'cursor:clear',
  CURSOR_STATE: 'cursor:state',
  CHAT_SEND: 'chat:send',
  CHAT_MESSAGE: 'chat:message',
  EXECUTION_RESULT: 'execution:result',
  FILES_UPDATE: 'files:update',
  PRESENCE_SNAPSHOT: 'presence:snapshot',
  PRESENCE_USER_ONLINE: 'presence:user-online',
  PRESENCE_USER_OFFLINE: 'presence:user-offline',
  ACCESS_REQUEST_CREATED: 'room:access-request-created',
  ACCESS_REQUEST_RESOLVED: 'room:access-request-resolved',
});
